//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace COM.WebSvc {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OraPKGSoap", Namespace="http://tempuri.org/")]
    public partial class OraPKG : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback Test_DBConnectOperationCompleted;
        
        private System.Threading.SendOrPostCallback SephirothOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ora_SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ora_MultiSelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ora_ModifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ora_MultiModifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ora_Select_ProcedureOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ora_Run_ProcedureOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ora_Run_Procedure_BlobOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ora_Modify_ProcedureOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OraPKG() {
            this.Url = "http://172.30.10.7/LMESPOP_WebService/OraPKG.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event Test_DBConnectCompletedEventHandler Test_DBConnectCompleted;
        
        /// <remarks/>
        public event SephirothCompletedEventHandler SephirothCompleted;
        
        /// <remarks/>
        public event Ora_SelectCompletedEventHandler Ora_SelectCompleted;
        
        /// <remarks/>
        public event Ora_MultiSelectCompletedEventHandler Ora_MultiSelectCompleted;
        
        /// <remarks/>
        public event Ora_ModifyCompletedEventHandler Ora_ModifyCompleted;
        
        /// <remarks/>
        public event Ora_MultiModifyCompletedEventHandler Ora_MultiModifyCompleted;
        
        /// <remarks/>
        public event Ora_Select_ProcedureCompletedEventHandler Ora_Select_ProcedureCompleted;
        
        /// <remarks/>
        public event Ora_Run_ProcedureCompletedEventHandler Ora_Run_ProcedureCompleted;
        
        /// <remarks/>
        public event Ora_Run_Procedure_BlobCompletedEventHandler Ora_Run_Procedure_BlobCompleted;
        
        /// <remarks/>
        public event Ora_Modify_ProcedureCompletedEventHandler Ora_Modify_ProcedureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test_DBConnect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test_DBConnect() {
            object[] results = this.Invoke("Test_DBConnect", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTest_DBConnect(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Test_DBConnect", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndTest_DBConnect(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Test_DBConnectAsync() {
            this.Test_DBConnectAsync(null);
        }
        
        /// <remarks/>
        public void Test_DBConnectAsync(object userState) {
            if ((this.Test_DBConnectOperationCompleted == null)) {
                this.Test_DBConnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTest_DBConnectOperationCompleted);
            }
            this.InvokeAsync("Test_DBConnect", new object[0], this.Test_DBConnectOperationCompleted, userState);
        }
        
        private void OnTest_DBConnectOperationCompleted(object arg) {
            if ((this.Test_DBConnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Test_DBConnectCompleted(this, new Test_DBConnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sephiroth", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Sephiroth() {
            object[] results = this.Invoke("Sephiroth", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSephiroth(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Sephiroth", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndSephiroth(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SephirothAsync() {
            this.SephirothAsync(null);
        }
        
        /// <remarks/>
        public void SephirothAsync(object userState) {
            if ((this.SephirothOperationCompleted == null)) {
                this.SephirothOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSephirothOperationCompleted);
            }
            this.InvokeAsync("Sephiroth", new object[0], this.SephirothOperationCompleted, userState);
        }
        
        private void OnSephirothOperationCompleted(object arg) {
            if ((this.SephirothCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SephirothCompleted(this, new SephirothCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ora_Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Ora_Select(string[] User_Info, string StrQry) {
            object[] results = this.Invoke("Ora_Select", new object[] {
                        User_Info,
                        StrQry});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOra_Select(string[] User_Info, string StrQry, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ora_Select", new object[] {
                        User_Info,
                        StrQry}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndOra_Select(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Ora_SelectAsync(string[] User_Info, string StrQry) {
            this.Ora_SelectAsync(User_Info, StrQry, null);
        }
        
        /// <remarks/>
        public void Ora_SelectAsync(string[] User_Info, string StrQry, object userState) {
            if ((this.Ora_SelectOperationCompleted == null)) {
                this.Ora_SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOra_SelectOperationCompleted);
            }
            this.InvokeAsync("Ora_Select", new object[] {
                        User_Info,
                        StrQry}, this.Ora_SelectOperationCompleted, userState);
        }
        
        private void OnOra_SelectOperationCompleted(object arg) {
            if ((this.Ora_SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ora_SelectCompleted(this, new Ora_SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ora_MultiSelect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Ora_MultiSelect(string[] User_Info, string[] StrDT, string[] StrQry) {
            object[] results = this.Invoke("Ora_MultiSelect", new object[] {
                        User_Info,
                        StrDT,
                        StrQry});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOra_MultiSelect(string[] User_Info, string[] StrDT, string[] StrQry, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ora_MultiSelect", new object[] {
                        User_Info,
                        StrDT,
                        StrQry}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndOra_MultiSelect(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Ora_MultiSelectAsync(string[] User_Info, string[] StrDT, string[] StrQry) {
            this.Ora_MultiSelectAsync(User_Info, StrDT, StrQry, null);
        }
        
        /// <remarks/>
        public void Ora_MultiSelectAsync(string[] User_Info, string[] StrDT, string[] StrQry, object userState) {
            if ((this.Ora_MultiSelectOperationCompleted == null)) {
                this.Ora_MultiSelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOra_MultiSelectOperationCompleted);
            }
            this.InvokeAsync("Ora_MultiSelect", new object[] {
                        User_Info,
                        StrDT,
                        StrQry}, this.Ora_MultiSelectOperationCompleted, userState);
        }
        
        private void OnOra_MultiSelectOperationCompleted(object arg) {
            if ((this.Ora_MultiSelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ora_MultiSelectCompleted(this, new Ora_MultiSelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ora_Modify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object Ora_Modify(string[] User_Info, string StrQry) {
            object[] results = this.Invoke("Ora_Modify", new object[] {
                        User_Info,
                        StrQry});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOra_Modify(string[] User_Info, string StrQry, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ora_Modify", new object[] {
                        User_Info,
                        StrQry}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndOra_Modify(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void Ora_ModifyAsync(string[] User_Info, string StrQry) {
            this.Ora_ModifyAsync(User_Info, StrQry, null);
        }
        
        /// <remarks/>
        public void Ora_ModifyAsync(string[] User_Info, string StrQry, object userState) {
            if ((this.Ora_ModifyOperationCompleted == null)) {
                this.Ora_ModifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOra_ModifyOperationCompleted);
            }
            this.InvokeAsync("Ora_Modify", new object[] {
                        User_Info,
                        StrQry}, this.Ora_ModifyOperationCompleted, userState);
        }
        
        private void OnOra_ModifyOperationCompleted(object arg) {
            if ((this.Ora_ModifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ora_ModifyCompleted(this, new Ora_ModifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ora_MultiModify", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object Ora_MultiModify(string[] User_Info, string[] StrQry) {
            object[] results = this.Invoke("Ora_MultiModify", new object[] {
                        User_Info,
                        StrQry});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOra_MultiModify(string[] User_Info, string[] StrQry, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ora_MultiModify", new object[] {
                        User_Info,
                        StrQry}, callback, asyncState);
        }
        
        /// <remarks/>
        public object EndOra_MultiModify(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void Ora_MultiModifyAsync(string[] User_Info, string[] StrQry) {
            this.Ora_MultiModifyAsync(User_Info, StrQry, null);
        }
        
        /// <remarks/>
        public void Ora_MultiModifyAsync(string[] User_Info, string[] StrQry, object userState) {
            if ((this.Ora_MultiModifyOperationCompleted == null)) {
                this.Ora_MultiModifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOra_MultiModifyOperationCompleted);
            }
            this.InvokeAsync("Ora_MultiModify", new object[] {
                        User_Info,
                        StrQry}, this.Ora_MultiModifyOperationCompleted, userState);
        }
        
        private void OnOra_MultiModifyOperationCompleted(object arg) {
            if ((this.Ora_MultiModifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ora_MultiModifyCompleted(this, new Ora_MultiModifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ora_Select_Procedure", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Ora_Select_Procedure(string[] User_Info, System.Data.DataSet DS_Para) {
            object[] results = this.Invoke("Ora_Select_Procedure", new object[] {
                        User_Info,
                        DS_Para});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOra_Select_Procedure(string[] User_Info, System.Data.DataSet DS_Para, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ora_Select_Procedure", new object[] {
                        User_Info,
                        DS_Para}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndOra_Select_Procedure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Ora_Select_ProcedureAsync(string[] User_Info, System.Data.DataSet DS_Para) {
            this.Ora_Select_ProcedureAsync(User_Info, DS_Para, null);
        }
        
        /// <remarks/>
        public void Ora_Select_ProcedureAsync(string[] User_Info, System.Data.DataSet DS_Para, object userState) {
            if ((this.Ora_Select_ProcedureOperationCompleted == null)) {
                this.Ora_Select_ProcedureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOra_Select_ProcedureOperationCompleted);
            }
            this.InvokeAsync("Ora_Select_Procedure", new object[] {
                        User_Info,
                        DS_Para}, this.Ora_Select_ProcedureOperationCompleted, userState);
        }
        
        private void OnOra_Select_ProcedureOperationCompleted(object arg) {
            if ((this.Ora_Select_ProcedureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ora_Select_ProcedureCompleted(this, new Ora_Select_ProcedureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ora_Run_Procedure", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Ora_Run_Procedure(string[] User_Info, System.Data.DataSet DS_Para) {
            object[] results = this.Invoke("Ora_Run_Procedure", new object[] {
                        User_Info,
                        DS_Para});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOra_Run_Procedure(string[] User_Info, System.Data.DataSet DS_Para, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ora_Run_Procedure", new object[] {
                        User_Info,
                        DS_Para}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndOra_Run_Procedure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Ora_Run_ProcedureAsync(string[] User_Info, System.Data.DataSet DS_Para) {
            this.Ora_Run_ProcedureAsync(User_Info, DS_Para, null);
        }
        
        /// <remarks/>
        public void Ora_Run_ProcedureAsync(string[] User_Info, System.Data.DataSet DS_Para, object userState) {
            if ((this.Ora_Run_ProcedureOperationCompleted == null)) {
                this.Ora_Run_ProcedureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOra_Run_ProcedureOperationCompleted);
            }
            this.InvokeAsync("Ora_Run_Procedure", new object[] {
                        User_Info,
                        DS_Para}, this.Ora_Run_ProcedureOperationCompleted, userState);
        }
        
        private void OnOra_Run_ProcedureOperationCompleted(object arg) {
            if ((this.Ora_Run_ProcedureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ora_Run_ProcedureCompleted(this, new Ora_Run_ProcedureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ora_Run_Procedure_Blob", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Ora_Run_Procedure_Blob(string Procude_Name, string[] Parameter_Name, int[] Parameter_Type, string[] Parameter_Value, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] photo) {
            object[] results = this.Invoke("Ora_Run_Procedure_Blob", new object[] {
                        Procude_Name,
                        Parameter_Name,
                        Parameter_Type,
                        Parameter_Value,
                        photo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOra_Run_Procedure_Blob(string Procude_Name, string[] Parameter_Name, int[] Parameter_Type, string[] Parameter_Value, byte[] photo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ora_Run_Procedure_Blob", new object[] {
                        Procude_Name,
                        Parameter_Name,
                        Parameter_Type,
                        Parameter_Value,
                        photo}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndOra_Run_Procedure_Blob(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Ora_Run_Procedure_BlobAsync(string Procude_Name, string[] Parameter_Name, int[] Parameter_Type, string[] Parameter_Value, byte[] photo) {
            this.Ora_Run_Procedure_BlobAsync(Procude_Name, Parameter_Name, Parameter_Type, Parameter_Value, photo, null);
        }
        
        /// <remarks/>
        public void Ora_Run_Procedure_BlobAsync(string Procude_Name, string[] Parameter_Name, int[] Parameter_Type, string[] Parameter_Value, byte[] photo, object userState) {
            if ((this.Ora_Run_Procedure_BlobOperationCompleted == null)) {
                this.Ora_Run_Procedure_BlobOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOra_Run_Procedure_BlobOperationCompleted);
            }
            this.InvokeAsync("Ora_Run_Procedure_Blob", new object[] {
                        Procude_Name,
                        Parameter_Name,
                        Parameter_Type,
                        Parameter_Value,
                        photo}, this.Ora_Run_Procedure_BlobOperationCompleted, userState);
        }
        
        private void OnOra_Run_Procedure_BlobOperationCompleted(object arg) {
            if ((this.Ora_Run_Procedure_BlobCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ora_Run_Procedure_BlobCompleted(this, new Ora_Run_Procedure_BlobCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ora_Modify_Procedure", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Ora_Modify_Procedure(string[] User_Info, System.Data.DataSet DS_Data) {
            object[] results = this.Invoke("Ora_Modify_Procedure", new object[] {
                        User_Info,
                        DS_Data});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginOra_Modify_Procedure(string[] User_Info, System.Data.DataSet DS_Data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Ora_Modify_Procedure", new object[] {
                        User_Info,
                        DS_Data}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndOra_Modify_Procedure(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void Ora_Modify_ProcedureAsync(string[] User_Info, System.Data.DataSet DS_Data) {
            this.Ora_Modify_ProcedureAsync(User_Info, DS_Data, null);
        }
        
        /// <remarks/>
        public void Ora_Modify_ProcedureAsync(string[] User_Info, System.Data.DataSet DS_Data, object userState) {
            if ((this.Ora_Modify_ProcedureOperationCompleted == null)) {
                this.Ora_Modify_ProcedureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOra_Modify_ProcedureOperationCompleted);
            }
            this.InvokeAsync("Ora_Modify_Procedure", new object[] {
                        User_Info,
                        DS_Data}, this.Ora_Modify_ProcedureOperationCompleted, userState);
        }
        
        private void OnOra_Modify_ProcedureOperationCompleted(object arg) {
            if ((this.Ora_Modify_ProcedureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ora_Modify_ProcedureCompleted(this, new Ora_Modify_ProcedureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Test_DBConnectCompletedEventHandler(object sender, Test_DBConnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Test_DBConnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Test_DBConnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SephirothCompletedEventHandler(object sender, SephirothCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SephirothCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SephirothCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ora_SelectCompletedEventHandler(object sender, Ora_SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ora_SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ora_SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ora_MultiSelectCompletedEventHandler(object sender, Ora_MultiSelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ora_MultiSelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ora_MultiSelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ora_ModifyCompletedEventHandler(object sender, Ora_ModifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ora_ModifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ora_ModifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ora_MultiModifyCompletedEventHandler(object sender, Ora_MultiModifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ora_MultiModifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ora_MultiModifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ora_Select_ProcedureCompletedEventHandler(object sender, Ora_Select_ProcedureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ora_Select_ProcedureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ora_Select_ProcedureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ora_Run_ProcedureCompletedEventHandler(object sender, Ora_Run_ProcedureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ora_Run_ProcedureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ora_Run_ProcedureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ora_Run_Procedure_BlobCompletedEventHandler(object sender, Ora_Run_Procedure_BlobCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ora_Run_Procedure_BlobCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ora_Run_Procedure_BlobCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Ora_Modify_ProcedureCompletedEventHandler(object sender, Ora_Modify_ProcedureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ora_Modify_ProcedureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ora_Modify_ProcedureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591